builds:
  - env:
      - CGO_ENABLED=0
      - ONLY_ACTIVE_ARCH=NO
    goos:
      - linux
      - darwin
    main: ./cmd/contractor
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
