builds:
  - goos:
    - linux
    - darwin
    - windows
    goarch:
    - 386
    - amd64
    main: ./cmd/contractor
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
