testers:
  graylog:
    url: https://graylog.setpartnerstv.ru/api
    username: 1geh46b37k3mib77lj8lt401mkah24d1alomosish521tsfqsuaf
    password: token
    spec_dir: ${PROJECT_DIR}/specs/e2e
    timeout: 5s

reporters:
  console: {}

variables:
