testers:
  graylog:
    url: https://graylog.setpartnerstv.ru/api
    username: 1geh46b37k3mib77lj8lt401mkah24d1alomosish521tsfqsuaf
    password: token
    spec_dir: ${PROJECT_DIR}/specs/e2e
    timeout: 5s
  open_api:
    type: oa2
    filename: ${PROJECT_DIR}/specs/oa2.yml
    base_url: ${URL_BASE}

reporters:
  console: {}

variables:
