// Code generated by go-swagger; DO NOT EDIT.

package decorators

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new decorators API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for decorators API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	SearchAbsolute(params *SearchAbsoluteParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SearchAbsoluteOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  SearchAbsolute messages search with absolute timerange

  Search for messages using an absolute timerange, specified as from/to with format yyyy-MM-ddTHH:mm:ss.SSSZ (e.g. 2014-01-23T15:34:49.000Z) or yyyy-MM-dd HH:mm:ss.
*/
func (a *Client) SearchAbsolute(params *SearchAbsoluteParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*SearchAbsoluteOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSearchAbsoluteParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "searchAbsolute",
		Method:             "GET",
		PathPattern:        "/search/universal/absolute",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &SearchAbsoluteReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*SearchAbsoluteOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for searchAbsolute: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
