// Code generated by MockGen. DO NOT EDIT.
// Source: runner.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	tester "github.com/byorty/contractor/tester"
	gomock "github.com/golang/mock/gomock"
)

// MockRunner is a mock of Runner interface.
type MockRunner struct {
	ctrl     *gomock.Controller
	recorder *MockRunnerMockRecorder
}

// MockRunnerMockRecorder is the mock recorder for MockRunner.
type MockRunnerMockRecorder struct {
	mock *MockRunner
}

// NewMockRunner creates a new mock instance.
func NewMockRunner(ctrl *gomock.Controller) *MockRunner {
	mock := &MockRunner{ctrl: ctrl}
	mock.recorder = &MockRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunner) EXPECT() *MockRunnerMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockRunner) Run(assertions tester.Asserter2List) tester.RunnerReportList {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", assertions)
	ret0, _ := ret[0].(tester.RunnerReportList)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockRunnerMockRecorder) Run(assertions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockRunner)(nil).Run), assertions)
}

// Setup mocks base method.
func (m *MockRunner) Setup(testCase tester.TestCase2) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Setup", testCase)
}

// Setup indicates an expected call of Setup.
func (mr *MockRunnerMockRecorder) Setup(testCase interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Setup", reflect.TypeOf((*MockRunner)(nil).Setup), testCase)
}
