name: deploy

on:
  push:
    tags:
      - '*'

jobs:
  releases:
    name: Release Go Binary
    runs-on: macos-latest
    env:
      APPNAME: contractor
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.0'
      - name: Install dependencies
        run: |
          cp -f .env.dist .env
          make install
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get checksum
        id: checksum
        run: |
          echo "::set-output name=value::$(cat dist/checksums.txt | grep Darwin_arm64 | cut -d ' ' -f1)"
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-name: ${{ env.APPNAME }}
          formula-path: ${{ env.APPNAME }}.rb
          homebrew-tap: byorty/homebrew-tap
          base-branch: master
          download-url: https://github.com/byorty/contractor/releases/download/${{ github.ref_name }}/${{ env.APPNAME }}_${{ github.ref_name }}_darwin_amd64.tar.gz
          download-sha256: "${{ steps.checksum.outputs.value }}"
          commit-message: |
            ${{ env.APPNAME }} ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          COMMITTER_TOKEN: ${{ secrets.TOKEN }}