name: deploy

on:
  push:
    tags:
      - '*'

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin]
        goarch: [arm64]
    env:
      APPNAME: contractor
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.TOKEN }}
      - name: Install dependencies
        run: |
          cp -f .env.dist .env
          make install
      - uses: wangyoucao577/go-release-action@v1.22
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: ./cmd/${{ env.APPNAME }}
          binary_name: ${{ env.APPNAME }}
      - name: Update Homebrew formula
        uses: toolmantim/tap-release@1.6
        with:
          url: https://github.com/byorty/contractor/releases/download/${{ env.GITHUB_REF }}/contractor-${{ env.GITHUB_REF }}-darwin-arm64.tar.gz
          tap: byorty/homebrew-contractor/contractor.rb
          template: |
            class Contractor < Formula
                homepage "https://github.com/byorty/contractor"
                desc "Reads the description document and generates test cases that will ensure that your application is compliant with its description"
                version  "$STABLE_VERSION"
                url      "$STABLE_ASSET_URL"
                sha256   "$STABLE_ASSET_SHA256"
                license "MIT"
                
                def install
                bin.install "contractor"
                end
            end