name: deploy

on:
  push:
    branches: [master]

jobs:
  macos-build:
    runs-on: macos-11
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: make install
      - name: Build contractor
        run: cp -f .env.dist .env && make build