name: deploy

env:
  APPNAME: contractor

on:
  push:
    tags:
      - '*'

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin]
        goarch: [arm64]
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.TOKEN }}
      - name: Install dependencies
        run: |
          cp -f .env.dist .env
          make install
      - uses: wangyoucao577/go-release-action@v1.22
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: ./cmd/${{ APPNAME }}
          binary_name: ${{ APPNAME }}
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.TOKEN }}
          org: byorty
          tap: byorty/${{ APPNAME }}
          formula: ${{ APPNAME }}
          tag: ${{ GITHUB_REF_NAME }}
          revision: ${{ GITHUB_SHA }}