name: deploy

on:
  push:
    tags:
      - '*'

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin]
        goarch: [arm64]
    env:
      APPNAME: contractor
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.TOKEN }}
      - name: Install dependencies
        run: |
          cp -f .env.dist .env
          make install
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-name: ${{ APPNAME }}
          formula-path: ${{ APPNAME }}.rb
          homebrew-tap: byorty/homebrew-tap
          base-branch: master
          download-url: https://github.com/byorty/contractor/releases/download/${{ env.GITHUB_REF }}/${{ APPNAME }}_${{ env.GITHUB_REF }}_Darwin_arm64.tar.gz
          commit-message: |
            ${{ APPNAME }} ${{ env.GITHUB_REF }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}