name: deploy

on:
  push:
    tags:
      - '*'

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: macos-11
    strategy:
      matrix:
        goos: [darwin]
        goarch: [arm64]
    env:
      APPNAME: contractor
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cp -f .env.dist .env
          make install
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-name: ${{ env.APPNAME }}
          formula-path: ${{ env.APPNAME }}.rb
          homebrew-tap: byorty/homebrew-tap
          base-branch: master
          download-url: https://github.com/byorty/contractor/releases/download/${{ github.ref_name }}/${{ env.APPNAME }}_${{ github.ref_name }}_Darwin_arm64.tar.gz
          commit-message: |
            ${{ env.APPNAME }} ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}